import "./style.css";
import { DartGame } from "./game/DartGame";

/** Helper to fetch an element by id, throwing if missing. */
function elById<T extends HTMLElement>(id: string): T {
  const el = document.getElementById(id);
  if (!el) throw new Error(`Missing element #${id}`);
  return el as T;
}

/** Build the DOM structure dynamically. This ensures that the app can run
 * inside a Devvit Web container where the index.html is generated by the
 * bundler. We create the HUD, toast, leaderboard and summary panels here. */
function buildDom(): void {
  const app = document.createElement("div");
  app.id = "app";

  // Stage container: holds the Three.js canvas and in-game overlays.
  // The HUD stays in normal flow (top bar) so it never covers the board.
  const stage = document.createElement("div");
  stage.id = "stage";
  // HUD
  const hud = document.createElement("div");
  hud.id = "hud";
  hud.innerHTML = `
    <div class="row"><span class="label">Score</span> <b id="score">0</b></div>
    <div class="row">
      <span class="label">Darts</span>
      <b id="darts">-</b>
      <div id="dartsPips" class="pips"></div>
    </div>
    <div class="row"><span class="label">Last</span> <b id="last">-</b></div>
    <div class="row"><span class="label">Cooldown</span> <b id="cooldown">0</b></div>
    <div class="row">
      <button id="btnNew">New game</button>
      <button id="btnLb">Leaderboard</button>
      <span class="label">(hold to aim; release to throw)</span>
    </div>
  `;
  const toast = document.createElement("div");
  toast.id = "toast";
  // Leaderboard overlay panel
  const lbPanel = document.createElement("div");
  lbPanel.id = "lbPanel";
  lbPanel.innerHTML = `
    <h2>Leaderboard</h2>
    <ul></ul>
    <button>Close</button>
  `;
  // Summary overlay panel
  const summaryPanel = document.createElement("div");
  summaryPanel.id = "summaryPanel";
  summaryPanel.innerHTML = `
    <h2>Round Complete</h2>
    <ul></ul>
    <button>New Game</button>
  `;
  // Append to app
  stage.appendChild(toast);
  stage.appendChild(lbPanel);
  stage.appendChild(summaryPanel);

  app.appendChild(hud);
  app.appendChild(stage);

  // Start panel overlay shown before the game begins. Provides a title,
  // brief instructions and a start button. When the start button is
  // clicked, this panel will be removed and the game will start.
  const startPanel = document.createElement("div");
  startPanel.id = "startPanel";
  startPanel.innerHTML = `
    <h1>REDARTULOUS</h1>
    <p>Aim for the highest score!</p>
    <p><em>Hold to aim, release to throw.</em></p>
    <button id="btnStart">Start Game</button>
  `;
  app.appendChild(startPanel);

  document.body.appendChild(app);
}

async function main(): Promise<void> {
  buildDom();
  const container = elById<HTMLDivElement>("stage");
  const game = new DartGame(
    container,
    {
      scoreEl: elById("score"),
      dartsEl: elById("darts"),
      dartsPipsEl: elById("dartsPips"),
      lastEl: elById("last"),
      btnNewEl: elById<HTMLButtonElement>("btnNew"),
      btnLbEl: elById<HTMLButtonElement>("btnLb"),
      toastEl: elById("toast"),
      cooldownEl: elById("cooldown"),
    },
    elById("lbPanel"),
    elById("summaryPanel")
  );
  // Defer starting the game until the user clicks the Start button. This
  // provides a pre‑game splash screen and prevents the game from
  // immediately making API requests. When the button is clicked, we
  // hide the start panel and call game.start().
  const startBtn = document.getElementById("btnStart");
  if (startBtn) {
    startBtn.addEventListener("click", async () => {
      // Hide the start panel
      const panel = document.getElementById("startPanel");
      if (panel) panel.style.display = "none";
      await game.start();
    });
  } else {
    // Fallback: if start button isn't found, just start immediately
    await game.start();
  }
}

void main();